package PRIMERO;
// Generated 07-ene-2017 17:15:57 by Hibernate Tools 5.2.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * Empleados generated by hbm2java
 */
public class Empleados implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2L;
	private BigDecimal empNo;
	private Departamentos departamentos;
	private String apellido;
	private String oficio;
	private BigDecimal dir;
	private Date fechaAlt;
	private Double salario;
	private Double comision;

	public Empleados() {
	}

	public Empleados(BigDecimal empNo, Departamentos departamentos) {
		this.empNo = empNo;
		this.departamentos = departamentos;
	}

	public Empleados(BigDecimal empNo, Departamentos departamentos, String apellido, String oficio, BigDecimal dir,
			Date fechaAlt, Double salario, Double comision) {
		this.empNo = empNo;
		this.departamentos = departamentos;
		this.apellido = apellido;
		this.oficio = oficio;
		this.dir = dir;
		this.fechaAlt = fechaAlt;
		this.salario = salario;
		this.comision = comision;
	}

	public BigDecimal getEmpNo() {
		return this.empNo;
	}

	public void setEmpNo(BigDecimal empNo) {
		this.empNo = empNo;
	}

	public Departamentos getDepartamentos() {
		return this.departamentos;
	}

	public void setDepartamentos(Departamentos departamentos) {
		this.departamentos = departamentos;
	}

	public String getApellido() {
		return this.apellido;
	}

	public void setApellido(String apellido) {
		this.apellido = apellido;
	}

	public String getOficio() {
		return this.oficio;
	}

	public void setOficio(String oficio) {
		this.oficio = oficio;
	}

	public BigDecimal getDir() {
		return this.dir;
	}

	public void setDir(BigDecimal dir) {
		this.dir = dir;
	}

	public Date getFechaAlt() {
		return this.fechaAlt;
	}

	public void setFechaAlt(Date fechaAlt) {
		this.fechaAlt = fechaAlt;
	}

	public Double getSalario() {
		return this.salario;
	}

	public void setSalario(Double salario) {
		this.salario = salario;
	}

	public Double getComision() {
		return this.comision;
	}

	public void setComision(Double comision) {
		this.comision = comision;
	}

}
